import com.android.build.api.variant.FilterConfiguration

import java.util.regex.Pattern

buildscript {

    ext.nav_version = "2.7.7" // Next version upgrade requires bump minSdk to 21

    dependencies { // Add third party gradle plugins
        classpath 'com.google.gms:google-services:4.3.15'    // Google Services plugin
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.6'

        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
    }
}

plugins {
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.protobuf' version '0.9.4'
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'kotlin-kapt'
apply plugin: "androidx.navigation.safeargs"
apply plugin: 'com.squareup.sqldelight'
apply plugin: 'kotlin-parcelize'

apply from: 'houston.gradle'
apply from: "${project.rootDir}/linters/checkstyle/check-android.gradle"
apply from: "${project.rootDir}/linters/pmd/check-android.gradle"

// spotbugs is kinda broken for android projects
// it doesnt recognize what it has to check from android settings and needs a lot of hacking to work
// https://github.com/spotbugs/spotbugs-gradle-plugin/issues/90
//apply from: "${project.rootDir}/linters/findbugs/check-android.gradle"


check.dependsOn 'lint'
tasks.matching { it.name.startsWith('lint') }.configureEach {task ->
    task.dependsOn(':common:animalsnifferMain')
}

/**
 * Insert quotes around string fields that are injected literally into code, like a C macro.
 */
static def quote(string) {
    return "\"" + string + "\""
}

/**
 * Returns a prefix of the current commit hash.
 */
static def commitTag() {
    return 'git rev-parse --short HEAD'.execute().text.trim().substring(0, 7)
}

/**
 * Returns the name of the current git branch.
 */
static def branchName() {
    return 'git rev-parse --abbrev-ref HEAD'.execute().text.trim()
}

/**
 * Configure external links for a given product flavor.
 */
static def configExternalLinks(productFlavor, String host) {
    String verifyPath = "/link/verify-v2/index.html"
    String authorizePath = "/link/authorize/index.html"
    String changePasswdPath = "/link/confirm/index.html"
    String rcLoginAuthPath = "/link/authorize-rc/index.html"
    String confirmAccountDeletionPath = "/link/confirm-account-deletion/index.html"

    // Required for AndroidManifest:
    productFlavor.resValue "string", "muun_link_host", host
    productFlavor.resValue "string", "verify_link_path", verifyPath
    productFlavor.resValue "string", "authorize_link_path", authorizePath
    productFlavor.resValue "string", "confirm_link_path", changePasswdPath
    productFlavor.resValue "string", "rc_login_authorize_link_path", rcLoginAuthPath
    productFlavor.resValue "string", "confirm_account_deletion_path", confirmAccountDeletionPath

    // Required for code access in action layer:
    productFlavor.buildConfigField "String", "MUUN_LINK_HOST", quote(host)
    productFlavor.buildConfigField "String", "VERIFY_LINK_PATH", quote(verifyPath)
    productFlavor.buildConfigField "String", "AUTHORIZE_LINK_PATH", quote(authorizePath)
    productFlavor.buildConfigField "String", "CONFIRM_LINK_PATH", quote(changePasswdPath)
    productFlavor.buildConfigField "String", "RC_LOGIN_AUTHORIZE_LINK_PATH", quote(rcLoginAuthPath)
    productFlavor.buildConfigField "String", "CONFIRM_ACCOUNT_DELETION_PATH", quote(confirmAccountDeletionPath)
}

android {
    signingConfigs {
        prod {
            def dogfoodKeystoreProps = new Properties()
            def keystorePropsFile = file("./dogfood-keystore.properties")
            if (keystorePropsFile.exists()) {
                dogfoodKeystoreProps.load(new FileInputStream(keystorePropsFile))
            }
            def keystoreFilePath = dogfoodKeystoreProps['keystoreFile']
            storeFile keystoreFilePath != null ? file(keystoreFilePath) : null
            storePassword dogfoodKeystoreProps['storePassword'] ?: ""
            keyAlias dogfoodKeystoreProps['keyAlias'] ?: ""
            keyPassword dogfoodKeystoreProps['keyPassword'] ?: ""
        }
    }

        // Debug application class, which is interpolated into AndroidManifest.xml
        defaultConfig {
        manifestPlaceholders = [mainApplicationClass: 'ApolloDebugApplication', usesCleartextTraffic: 'true']

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField("String", "COMMIT", quote(commitTag()))
        buildConfigField("String", "BRANCH", quote(branchName()))
        buildConfigField("boolean", "PRODUCTION", "false")
        buildConfigField("boolean", "RELEASE", "false")
    }

            