name: Compilar APK de Muun

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Dar permisos de ejecución a Gradle
      run: chmod +x gradlew

    - name: Compilar APK Debug
      run: ./gradlew assembleDebug

    - name: Subir APK Generado
      uses: actions/upload-artifact@v4
      with:
        name: meen-beta
        path: android/apollo/build/outputs/apk/debug/meen-beta.apk
