    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Create google-services.json
      run: |
        mkdir -p android/apolloui/src/dogfood
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/apolloui/src/dogfood/google-services.json
        cp android/apolloui/src/dogfood/google-services.json android/apolloui/google-services.json
